<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="conml" nsURI="http://conml.ecore" nsPrefix="conml">
  <eClassifiers xsi:type="ecore:EClass" name="Model" abstract="true" eSuperTypes="#//NamedElement #//DescribableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double" defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DefaultLanguage" lowerBound="1"
        eType="#//Language"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tags" upperBound="-1" eType="#//Tag"
        eOpposite="#//Tag/Model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Languages" upperBound="-1"
        eType="#//Language" eOpposite="#//Language/Model"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelPart" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" abstract="true" eSuperTypes="#//ModelPart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tags" upperBound="-1" eType="#//Tag"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="MetaInformationObjects"
        upperBound="-1" eType="#//instances/Object" eOpposite="#//instances/Object/DocumentedElements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag" eSuperTypes="#//ModelPart #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Model" lowerBound="1" eType="#//Model"
        eOpposite="#//Model/Tags"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Language" eSuperTypes="#//ModelPart #//NamedElement #//DescribableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Model" lowerBound="1" eType="#//Model"
        eOpposite="#//Model/Languages"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetaInformation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Domain">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Models" upperBound="-1"
        eType="#//Model" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Parts" upperBound="-1"
        eType="#//ModelPart" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DescribableElement" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefinableElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="definition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommentableElement" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comments" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="types" nsURI="http://types.ecore" nsPrefix="types">
    <eClassifiers xsi:type="ecore:EClass" name="TypeModel" eSuperTypes="#//Model">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ConformingInstanceModel"
          eType="#//instances/InstanceModel" eOpposite="#//instances/InstanceModel/ConformedTypeModels"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="BaseTypeModel" eType="#//types/TypeModel"
          eOpposite="#//types/TypeModel/ParticularTypeModels"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ParticularTypeModels"
          upperBound="-1" eType="#//types/TypeModel" eOpposite="#//types/TypeModel/BaseTypeModel"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SubjectiveAspect" eType="#//types/Class"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="TemporalAspect" eType="#//types/Class"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Elements" upperBound="-1"
          eType="#//types/TypeModelElement" eOpposite="#//types/TypeModelElement/TypeModel"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" eSuperTypes="#//types/TypeModelElement #//NamedElement #//DefinableElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//types/Type #//CommentableElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="usedAsTemporalAspect"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="usedAsSubjectiveAspect"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Generalizations" upperBound="-1"
          eType="#//types/Generalization" eOpposite="#//types/Generalization/SpecializedClasses"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Specialization" eType="#//types/Generalization"
          eOpposite="#//types/Generalization/GeneralizedClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="DominantGeneralization"
          eType="#//types/Generalization" eOpposite="#//types/Generalization/DominatedClasses"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="InstanceObjects" upperBound="-1"
          eType="#//instances/Object" eOpposite="#//instances/Object/InstancedClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Package" eType="#//types/Package"
          eOpposite="#//types/Package/ContainedClasses"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Properties" upperBound="-1"
          eType="#//types/Property" containment="true" eOpposite="#//types/Property/OwnerClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Attributes" upperBound="-1"
          eType="#//types/Attribute" containment="true" eOpposite="#//types/Attribute/OwnerClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemiAssociations" upperBound="-1"
          eType="#//types/SemiAssociation" containment="true" eOpposite="#//types/SemiAssociation/OwnerClass"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Generalization" eSuperTypes="#//types/TypeModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="discriminant" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SpecializedClasses" lowerBound="1"
          upperBound="-1" eType="#//types/Class" eOpposite="#//types/Class/Generalizations"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="GeneralizedClass" lowerBound="1"
          eType="#//types/Class" eOpposite="#//types/Class/Specialization"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="DominatedClasses" upperBound="-1"
          eType="#//types/Class" eOpposite="#//types/Class/DominantGeneralization"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="discriminantDisplayed"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
          defaultValueLiteral="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Feature" abstract="true" eSuperTypes="#//types/Type">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumCardinality" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sorted" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="temporal" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="subjective" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="constant" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumCardinality" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumeratedType" eSuperTypes="#//CommentableElement #//types/DataType #//types/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="OwnedItems" upperBound="-1"
          eType="#//types/EnumeratedItem" containment="true" eOpposite="#//types/EnumeratedItem/OwnerType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SubTypes" upperBound="-1"
          eType="#//types/EnumeratedType" eOpposite="#//types/EnumeratedType/SuperType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SuperType" eType="#//types/EnumeratedType"
          eOpposite="#//types/EnumeratedType/SubTypes"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Package" eType="#//types/Package"
          eOpposite="#//types/Package/EnumeratedTypes"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeModelElement" abstract="true"
        eSuperTypes="#//ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="TypeModel" lowerBound="1"
          eType="#//types/TypeModel" eOpposite="#//types/TypeModel/Elements"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="#//types/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="PrimarySemiAssociation"
          lowerBound="1" eType="#//types/SemiAssociation" eOpposite="#//types/SemiAssociation/PrimaryInAssociation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SecondarySemiAssociation"
          lowerBound="1" eType="#//types/SemiAssociation" eOpposite="#//types/SemiAssociation/SecondaryInAssociation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="InstanceLinks" upperBound="-1"
          eType="#//instances/Link" eOpposite="#//instances/Link/InstancedAssociation"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="compact" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="#//types/TypeModelElement #//NamedElement #//DescribableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ContainedClasses" upperBound="-1"
          eType="#//types/Class" eOpposite="#//types/Class/Package"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="EnumeratedTypes" upperBound="-1"
          eType="#//types/EnumeratedType" eOpposite="#//types/EnumeratedType/Package"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SubPackages" upperBound="-1"
          eType="#//types/Package" eOpposite="#//types/Package/ContainerPackage"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ContainerPackage" eType="#//types/Package"
          eOpposite="#//types/Package/SubPackages"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="overall" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//types/Feature">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="multilingual" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="InstanceValueSets" upperBound="-1"
          eType="#//instances/ValueSet" eOpposite="#//instances/ValueSet/InstancedAttribute"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="OwnerClass" lowerBound="1"
          eType="#//types/Class" eOpposite="#//types/Class/Attributes"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="RedefinedAttribute" eType="#//types/Attribute"
          eOpposite="#//types/Attribute/RedefiningAttribute"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="RedefiningAttribute"
          eType="#//types/Attribute" eOpposite="#//types/Attribute/RedefinedAttribute"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="datatype" lowerBound="1"
          eType="#//types/DataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="BaseDataType">
      <eLiterals name="Boolean"/>
      <eLiterals name="Number" value="1"/>
      <eLiterals name="Text" value="2"/>
      <eLiterals name="Time" value="3"/>
      <eLiterals name="Data" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SemiAssociation" eSuperTypes="#//types/Feature">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="whole" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="strong" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="PrimaryInAssociation"
          eType="#//types/Association" eOpposite="#//types/Association/PrimarySemiAssociation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SecondaryInAssociation"
          eType="#//types/Association" eOpposite="#//types/Association/SecondarySemiAssociation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="InstanceReferenceSets"
          upperBound="-1" eType="#//instances/ReferenceSet" eOpposite="#//instances/ReferenceSet/InstancedSemiAssociation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="InverseSemiAssociation"
          lowerBound="1" eType="#//types/SemiAssociation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ReferredClass" lowerBound="1"
          eType="#//types/Class"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="RedefinedSemiAssociation"
          eType="#//types/SemiAssociation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="OwnerClass" lowerBound="1"
          eType="#//types/Class" eOpposite="#//types/Class/SemiAssociations"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameDisplayed" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="roleDisplayed" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//types/Feature">
      <eStructuralFeatures xsi:type="ecore:EReference" name="RedefinedProperty" eType="#//types/Property"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="OwnerClass" lowerBound="1"
          eType="#//types/Class" eOpposite="#//types/Class/Properties"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SimpleDataType" eSuperTypes="#//types/DataType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="base" lowerBound="1"
          eType="#//types/BaseDataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumeratedItem" eSuperTypes="#//NamedElement #//DefinableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="OwnerType" lowerBound="1"
          eType="#//types/EnumeratedType" eOpposite="#//types/EnumeratedType/OwnedItems"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SubItems" upperBound="-1"
          eType="#//types/EnumeratedItem" eOpposite="#//types/EnumeratedItem/SuperItem"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SuperItem" eType="#//types/EnumeratedItem"
          eOpposite="#//types/EnumeratedItem/SubItems"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataType" abstract="true" interface="true"
        eSuperTypes="#//ModelPart #//NamedElement"/>
  </eSubpackages>
  <eSubpackages name="instances" nsURI="http://instances.ecore" nsPrefix="instances">
    <eClassifiers xsi:type="ecore:EClass" name="Instance" abstract="true" eSuperTypes="#//instances/InstanceModelElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Facet" abstract="true" eSuperTypes="#//instances/InstanceModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="certainty" lowerBound="1"
          eType="#//instances/DegreeOfCertainty"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="#//instances/Facet">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ReferredObject" lowerBound="1"
          eType="#//instances/Object" eOpposite="#//instances/Object/IsReferredByReferences"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="PrimaryLink" eType="#//instances/Link"
          eOpposite="#//instances/Link/PrimaryReference"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SecondaryLink" eType="#//instances/Link"
          eOpposite="#//instances/Link/SecondaryReference"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="OwnerReferenceSet" lowerBound="1"
          eType="#//instances/ReferenceSet" eOpposite="#//instances/ReferenceSet/References"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="InverseReference" lowerBound="1"
          eType="#//instances/Reference"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InstanceModelElement" abstract="true"
        eSuperTypes="#//ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="InstanceModel" lowerBound="1"
          eType="#//instances/InstanceModel" eOpposite="#//instances/InstanceModel/Elements"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DegreeOfCertainty">
      <eLiterals name="Certain"/>
      <eLiterals name="Probable" value="1"/>
      <eLiterals name="Possible" value="2"/>
      <eLiterals name="Improbable" value="3"/>
      <eLiterals name="Impossible" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InstanceModel" eSuperTypes="#//Model">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ConformedTypeModels"
          lowerBound="1" upperBound="-1" eType="#//types/TypeModel" eOpposite="#//types/TypeModel/ConformingInstanceModel"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Elements" upperBound="-1"
          eType="#//instances/InstanceModelElement" eOpposite="#//instances/InstanceModelElement/InstanceModel"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ValueSet" eSuperTypes="#//instances/FacetSet">
      <eStructuralFeatures xsi:type="ecore:EReference" name="InstancedAttribute" lowerBound="1"
          eType="#//types/Attribute" eOpposite="#//types/Attribute/InstanceValueSets"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Values" upperBound="-1"
          eType="#//instances/Value" containment="true" eOpposite="#//instances/Value/OwnerValueSet"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enumeratedItemValueDisplay"
          lowerBound="1" eType="#//instances/EnumeratedItemValueDisplay" defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Owner" lowerBound="1"
          eType="#//instances/Object" eOpposite="#//instances/Object/ValueSets"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReferenceSet" eSuperTypes="#//instances/FacetSet">
      <eStructuralFeatures xsi:type="ecore:EReference" name="InstancedSemiAssociation"
          lowerBound="1" eType="#//types/SemiAssociation" eOpposite="#//types/SemiAssociation/InstanceReferenceSets"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="References" upperBound="-1"
          eType="#//instances/Reference" containment="true" eOpposite="#//instances/Reference/OwnerReferenceSet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Owner" lowerBound="1"
          eType="#//instances/Object" eOpposite="#//instances/Object/ReferenceSets"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Object" eSuperTypes="#//instances/Instance">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="certainty" lowerBound="1"
          eType="#//instances/DegreeOfCertainty"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="InstancedClass" lowerBound="1"
          eType="#//types/Class" eOpposite="#//types/Class/InstanceObjects"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="IsReferredByReferences"
          upperBound="-1" eType="#//instances/Reference" eOpposite="#//instances/Reference/ReferredObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ReferenceSets" upperBound="-1"
          eType="#//instances/ReferenceSet" containment="true" eOpposite="#//instances/ReferenceSet/Owner"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="DocumentedElements" upperBound="-1"
          eType="#//ModelElement" eOpposite="#//ModelElement/MetaInformationObjects"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="documenting" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SubjectiveExistentialQualifer"
          eType="#//instances/QualifierObject" eOpposite="#//instances/QualifierObject/SubjectiveQualifiedObjects"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="TemporalExistentialQualifier"
          eType="#//instances/QualifierObject" eOpposite="#//instances/QualifierObject/TemporalQualifiedObjects"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ValueSets" upperBound="-1"
          eType="#//instances/ValueSet" containment="true" eOpposite="#//instances/ValueSet/Owner"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//instances/Instance">
      <eStructuralFeatures xsi:type="ecore:EReference" name="InstancedAssociation"
          lowerBound="1" eType="#//types/Association" eOpposite="#//types/Association/InstanceLinks"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="PrimaryReference" lowerBound="1"
          eType="#//instances/Reference" eOpposite="#//instances/Reference/PrimaryLink"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SecondaryReference" lowerBound="1"
          eType="#//instances/Reference" eOpposite="#//instances/Reference/SecondaryLink"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="compact" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Value" abstract="true" eSuperTypes="#//instances/Facet">
      <eStructuralFeatures xsi:type="ecore:EReference" name="OwnerValueSet" lowerBound="1"
          eType="#//instances/ValueSet" eOpposite="#//instances/ValueSet/Values"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unknown" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FacetSet" abstract="true" eSuperTypes="#//instances/Instance">
      <eStructuralFeatures xsi:type="ecore:EReference" name="TranslationQualifiers"
          upperBound="-1" eType="#//Language"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="PerspectiveQualifier"
          eType="#//instances/QualifierObject" eOpposite="#//instances/QualifierObject/PerspectiveQualifiedFacetSets"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="PhaseQualifier" eType="#//instances/QualifierObject"
          eOpposite="#//instances/QualifierObject/PhaseQualifiedFacetSets"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="EnumeratedItemValueDisplay">
      <eLiterals name="ABSOLUTE"/>
      <eLiterals name="FULL_NAME" value="1"/>
      <eLiterals name="FULLY_QUALIFIED_NAME" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TextValue" eSuperTypes="#//instances/Value">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanValue" eSuperTypes="#//instances/Value">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TimeValue" eSuperTypes="#//instances/Value">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NumberValue" eSuperTypes="#//instances/Value">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataValue" eSuperTypes="#//instances/Value">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnySimpleType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumValue" eSuperTypes="#//instances/Value">
      <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//types/EnumeratedItem"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QualifierObject" eSuperTypes="#//instances/Object">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifier" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SubjectiveQualifiedObjects"
          upperBound="-1" eType="#//instances/Object" eOpposite="#//instances/Object/SubjectiveExistentialQualifer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="TemporalQualifiedObjects"
          upperBound="-1" eType="#//instances/Object" eOpposite="#//instances/Object/TemporalExistentialQualifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="PerspectiveQualifiedFacetSets"
          upperBound="-1" eType="#//instances/FacetSet" eOpposite="#//instances/FacetSet/PerspectiveQualifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="PhaseQualifiedFacetSets"
          eType="#//instances/FacetSet" eOpposite="#//instances/FacetSet/PhaseQualifier"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
