<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="conml" nsURI="http://conml.ecore" nsPrefix="conml">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double" defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="New model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Elements" upperBound="-1"
        eType="#//ModelElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Languages" upperBound="-1"
        eType="#//Language" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DefaultLanguage" lowerBound="1"
        eType="#//Language"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tags" upperBound="-1" eType="#//Tag"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelPart" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" abstract="true" eSuperTypes="#//ModelPart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tags" upperBound="-1" eType="#//Tag"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DocumentingObjects" upperBound="-1"
        eType="#//instances/Object"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag" eSuperTypes="#//ModelPart">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Language" eSuperTypes="#//ModelPart">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eSubpackages name="types" nsURI="http://types.ecore" nsPrefix="types">
    <eClassifiers xsi:type="ecore:EClass" name="TypeModel" eSuperTypes="#//Model">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ConformingInstanceModel"
          eType="#//instances/InstanceModel" eOpposite="#//instances/InstanceModel/ConformedTypeModels"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ExtendedTypeModel" eType="#//types/TypeModel"
          eOpposite="#//types/TypeModel/ExtendingTypeModels"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ExtendingTypeModels"
          upperBound="-1" eType="#//types/TypeModel" eOpposite="#//types/TypeModel/ExtendedTypeModel"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ParticularInTypeModel"
          eType="#//types/TypeModel" eOpposite="#//types/TypeModel/HasParticularTypeModels"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="HasParticularTypeModels"
          upperBound="-1" eType="#//types/TypeModel" eOpposite="#//types/TypeModel/ParticularInTypeModel"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SubjectiveAspect" eType="#//types/Class"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="TemporalAspect" eType="#//types/Class"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" eSuperTypes="#//types/TypeModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="definition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//types/Type">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="usedAsTemporalAspect"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="usedAsSubjectiveAspect"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Generalization" upperBound="-1"
          eType="#//types/Generalization" eOpposite="#//types/Generalization/SpecializedClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Specialization" eType="#//types/Generalization"
          eOpposite="#//types/Generalization/GeneralizedClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="DominantGeneralization"
          eType="#//types/Generalization" eOpposite="#//types/Generalization/DominatesInheritanceOn"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Semiassociations" upperBound="-1"
          eType="#//types/SemiAssociation" containment="true" eOpposite="#//types/SemiAssociation/Owner"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="InstanceObjects" upperBound="-1"
          eType="#//instances/Object" eOpposite="#//instances/Object/InstancedClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Package" eType="#//types/Package"
          eOpposite="#//types/Package/ContainedClasses"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Properties" upperBound="-1"
          eType="#//types/Property" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Attributes" upperBound="-1"
          eType="#//types/Attribute" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Generalization" eSuperTypes="#//types/TypeModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="discriminant" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SpecializedClass" lowerBound="1"
          upperBound="-1" eType="#//types/Class" eOpposite="#//types/Class/Generalization"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="GeneralizedClass" lowerBound="1"
          eType="#//types/Class" eOpposite="#//types/Class/Specialization"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="DominatesInheritanceOn"
          lowerBound="1" upperBound="-1" eType="#//types/Class" eOpposite="#//types/Class/DominantGeneralization"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Feature" abstract="true" eSuperTypes="#//types/Type">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumCardinality" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumCardinality" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sorted" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="temporal" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="subjective" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="constant" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="RedefinedFeature" eType="#//types/Feature"
          eOpposite="#//types/Feature/RedefinedByFeatures"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="RedefinedByFeatures"
          upperBound="-1" eType="#//types/Feature" eOpposite="#//types/Feature/RedefinedFeature"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumeratedType" eSuperTypes="#//types/DataType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="OwnedItems" upperBound="-1"
          eType="#//types/EnumeratedItem" containment="true" eOpposite="#//types/EnumeratedItem/Owner"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SpecializedByEnumeratedTypes"
          upperBound="-1" eType="#//types/EnumeratedType" eOpposite="#//types/EnumeratedType/SpecializesFromEnumeratedType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SpecializesFromEnumeratedType"
          eType="#//types/EnumeratedType" eOpposite="#//types/EnumeratedType/SpecializedByEnumeratedTypes"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Package" eType="#//types/Package"
          eOpposite="#//types/Package/EnumeratedTypes"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeModelElement" abstract="true"
        eSuperTypes="#//ModelElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="#//types/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="PrimarySemiAssociation"
          lowerBound="1" eType="#//types/SemiAssociation" eOpposite="#//types/SemiAssociation/PrimaryInAssociation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SecondarySemiAssociation"
          lowerBound="1" eType="#//types/SemiAssociation" eOpposite="#//types/SemiAssociation/SecondaryInAssociation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="InstanceLinks" upperBound="-1"
          eType="#//instances/Link" eOpposite="#//instances/Link/InstancedAssociation"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="compact" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="#//types/TypeModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ContainedClasses" upperBound="-1"
          eType="#//types/Class" eOpposite="#//types/Class/Package"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="EnumeratedTypes" upperBound="-1"
          eType="#//types/EnumeratedType" eOpposite="#//types/EnumeratedType/Package"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SubPackages" upperBound="-1"
          eType="#//types/Package" eOpposite="#//types/Package/ContainerPackage"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ContainerPackage" eType="#//types/Package"
          eOpposite="#//types/Package/SubPackages"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="overall" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//types/Feature">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="multilingual" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="InstanceValueSets" upperBound="-1"
          eType="#//instances/ValueSet" eOpposite="#//instances/ValueSet/InstancedAttribute"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Datatype" lowerBound="1"
          eType="#//types/DataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="BaseDataType">
      <eLiterals name="Boolean"/>
      <eLiterals name="Number" value="1"/>
      <eLiterals name="Text" value="2"/>
      <eLiterals name="Time" value="3"/>
      <eLiterals name="Data" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SemiAssociation" eSuperTypes="#//types/Feature">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="whole" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="strong" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Owner" lowerBound="1"
          eType="#//types/Class" eOpposite="#//types/Class/Semiassociations"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="PrimaryInAssociation"
          eType="#//types/Association" eOpposite="#//types/Association/PrimarySemiAssociation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SecondaryInAssociation"
          eType="#//types/Association" eOpposite="#//types/Association/SecondarySemiAssociation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="InstanceReferenceSets"
          upperBound="-1" eType="#//instances/ReferenceSet" eOpposite="#//instances/ReferenceSet/InstancedSemiAssociation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="InverseSemiAssociation"
          lowerBound="1" eType="#//types/SemiAssociation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ReferredClass" lowerBound="1"
          eType="#//types/Class"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//types/Feature"/>
    <eClassifiers xsi:type="ecore:EClass" name="SimpleDataType" eSuperTypes="#//types/DataType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="base" lowerBound="1"
          eType="#//types/BaseDataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="#//types/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="EnumeratedItem">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="absoluteName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="definition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Owner" lowerBound="1"
          eType="#//types/EnumeratedType" eOpposite="#//types/EnumeratedType/OwnedItems"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SuperItemOfEnumeratedItems"
          upperBound="-1" eType="#//types/EnumeratedItem" eOpposite="#//types/EnumeratedItem/SubItemOfEnumeratedItem"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SubItemOfEnumeratedItem"
          eType="#//types/EnumeratedItem" eOpposite="#//types/EnumeratedItem/SuperItemOfEnumeratedItems"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="instances" nsURI="http://instances.ecore" nsPrefix="instances">
    <eClassifiers xsi:type="ecore:EClass" name="Instance" abstract="true" eSuperTypes="#//instances/InstanceModelElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Facet" abstract="true" eSuperTypes="#//instances/InstanceModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="certainty" lowerBound="1"
          eType="#//instances/DegreeOfCertainty"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="IsOwnedBy" lowerBound="1"
          eType="#//instances/FacetSet" eOpposite="#//instances/FacetSet/IsComposedOf"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="#//instances/Facet">
      <eStructuralFeatures xsi:type="ecore:EReference" name="RefersTo" lowerBound="1"
          eType="#//instances/Object" eOpposite="#//instances/Object/IsOppositeIn"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inverse" eType="#//instances/Reference"
          eOpposite="#//instances/Reference/isInverseOf"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="isInverseOf" eType="#//instances/Reference"
          eOpposite="#//instances/Reference/inverse"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="IsPrimaryIn" eType="#//instances/Link"
          eOpposite="#//instances/Link/HasPrimary"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="IsSecondaryIn" eType="#//instances/Link"
          eOpposite="#//instances/Link/HasSecondary"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InstanceModelElement" abstract="true"
        eSuperTypes="#//ModelElement"/>
    <eClassifiers xsi:type="ecore:EEnum" name="DegreeOfCertainty">
      <eLiterals name="Certain"/>
      <eLiterals name="Probable" value="1"/>
      <eLiterals name="Possible" value="2"/>
      <eLiterals name="Improbable" value="3"/>
      <eLiterals name="Impossible" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InstanceModel" eSuperTypes="#//Model">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ConformedTypeModels"
          lowerBound="1" upperBound="-1" eType="#//types/TypeModel" eOpposite="#//types/TypeModel/ConformingInstanceModel"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ValueSet" eSuperTypes="#//instances/FacetSet">
      <eStructuralFeatures xsi:type="ecore:EReference" name="InstancedAttribute" lowerBound="1"
          eType="#//types/Attribute" eOpposite="#//types/Attribute/InstanceValueSets"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Owner" lowerBound="1"
          eType="#//instances/Object" eOpposite="#//instances/Object/OwnedValueSets"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReferenceSet" eSuperTypes="#//instances/FacetSet">
      <eStructuralFeatures xsi:type="ecore:EReference" name="InstancedSemiAssociation"
          lowerBound="1" eType="#//types/SemiAssociation" eOpposite="#//types/SemiAssociation/InstanceReferenceSets"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Owner" lowerBound="1"
          eType="#//instances/Object" eOpposite="#//instances/Object/OwnedReferenceSets"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Object" eSuperTypes="#//instances/Instance">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="certainty" lowerBound="1"
          eType="#//instances/DegreeOfCertainty"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="InstancedClass" lowerBound="1"
          eType="#//types/Class" eOpposite="#//types/Class/InstanceObjects"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="OwnedValueSets" upperBound="-1"
          eType="#//instances/ValueSet" eOpposite="#//instances/ValueSet/Owner"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="OwnedReferenceSets" upperBound="-1"
          eType="#//instances/ReferenceSet" eOpposite="#//instances/ReferenceSet/Owner"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="IsOppositeIn" upperBound="-1"
          eType="#//instances/Reference" eOpposite="#//instances/Reference/RefersTo"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="TemporalExistentialQualifier"
          eType="#//instances/Object"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SubjectiveExistentialQualifer"
          eType="#//instances/Object"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//instances/Instance">
      <eStructuralFeatures xsi:type="ecore:EReference" name="InstancedAssociation"
          lowerBound="1" eType="#//types/Association" eOpposite="#//types/Association/InstanceLinks"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="HasPrimary" eType="#//instances/Reference"
          eOpposite="#//instances/Reference/IsPrimaryIn"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="HasSecondary" eType="#//instances/Reference"
          eOpposite="#//instances/Reference/IsSecondaryIn"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Value" eSuperTypes="#//instances/Facet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="contents" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnySimpleType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FacetSet" abstract="true" eSuperTypes="#//instances/Instance">
      <eStructuralFeatures xsi:type="ecore:EReference" name="IsComposedOf" upperBound="-1"
          eType="#//instances/Facet" eOpposite="#//instances/Facet/IsOwnedBy"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="TranslationQualifiers"
          upperBound="-1" eType="#//Language"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="PhaseQualifier" eType="#//instances/Object"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="PerspectiveQualifier"
          eType="#//instances/Object"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
