/**
 *
 * $Id$
 */
package conml.instances.validation;

import conml.instances.DegreeOfCertainty;
import conml.instances.FacetSet;

/**
 * A sample validator interface for {@link conml.instances.Facet}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FacetValidator {
	boolean validate();

	boolean validateCertainty(DegreeOfCertainty value);
	boolean validateOwnerSet(FacetSet value);

  boolean validateIsOwnedBy(FacetSet value);
}
