/**
 *
 * $Id$
 */
package conml.instances.validation;

import conml.instances.Reference;

import conml.types.Association;

/**
 * A sample validator interface for {@link conml.instances.Link}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LinkValidator {
	boolean validate();

	boolean validateInstancedAssociation(Association value);

  boolean validatePrimaryReference(Reference value);

  boolean validateSecondaryReference(Reference value);

    boolean validateIsInstanceOf(Association value);
	boolean validateHasPrimary(Reference value);
	boolean validateHasSecondary(Reference value);
}
