/**
 *
 * $Id$
 */
package conml.instances.validation;

import conml.instances.FacetSet;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link conml.instances.QualifyingObject}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface QualifyingObjectValidator {
	boolean validate();

	boolean validateQualifier(String value);
	boolean validateSubjectiveQualifiedObjects(EList<conml.instances.Object> value);
	boolean validateTemporalQualifiedObjects(EList<conml.instances.Object> value);
	boolean validatePerspectiveQualifiedFacetSets(EList<FacetSet> value);
	boolean validatePhaseQualifiedFacetSets(FacetSet value);
}
