/**
 *
 * $Id$
 */
package conml.instances.validation;

import conml.instances.Reference;
import conml.types.SemiAssociation;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link conml.instances.ReferenceSet}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ReferenceSetValidator {
	boolean validate();

	boolean validateInstancedSemiAssociation(SemiAssociation value);

  boolean validateReferences(EList<Reference> value);

    boolean validateIsAnInstanceOf(SemiAssociation value);
	boolean validateOwner(conml.instances.Object value);
}
