/**
 *
 * $Id$
 */
package conml.instances.validation;

import conml.instances.Link;
import conml.instances.Reference;

/**
 * A sample validator interface for {@link conml.instances.Reference}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ReferenceValidator {
	boolean validate();

	boolean validateReferredObject(conml.instances.Object value);

  boolean validateRefersTo(conml.instances.Object value);
	boolean validateInverse(Reference value);
	boolean validateIsInverseOfReference(Reference value);

  boolean validatePrimaryInLink(Link value);

  boolean validateSecondaryLink(Link value);

  boolean validateIsInverseOf(Reference value);
	boolean validateIsPrimaryIn(Link value);
	boolean validateIsSecondaryIn(Link value);
}
