/**
 *
 * $Id$
 */
package conml.types.validation;

import conml.types.EnumeratedItem;
import conml.types.EnumeratedType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link conml.types.EnumeratedType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EnumeratedTypeValidator {
	boolean validate();

	boolean validateOwnsItems(EList<EnumeratedItem> value);
	boolean validateHasItems(EList<EnumeratedItem> value);
	boolean validateIsSpecializedBy(EList<EnumeratedType> value);
	boolean validateSpecializesFrom(EnumeratedType value);
	boolean validateBelongsToPackage(conml.types.Package value);
}
