/**
 *
 * $Id$
 */
package conml.types.validation;

import conml.instances.ReferenceSet;

import conml.types.Association;
import conml.types.SemiAssociation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link conml.types.SemiAssociation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SemiAssociationValidator {
	boolean validate();

	boolean validateRole(String value);
	boolean validateIsWhole(boolean value);
	boolean validateIsStrong(boolean value);
	boolean validateAssignedTo(EList<conml.types.Class> value);
	boolean validateOwner(conml.types.Class value);
	boolean validateRefersTo(conml.types.Class value);
	boolean validateIsInverseOf(SemiAssociation value);
	boolean validateInverse(SemiAssociation value);
	boolean validateIsPrimaryIn(Association value);
	boolean validateIsSecondaryIn(Association value);
	boolean validateHasInstanceReferenceSets(EList<ReferenceSet> value);
}
