/**
 *
 * $Id$
 */
package conml.types.validation;

import conml.types.BaseDataType;

/**
 * A sample validator interface for {@link conml.types.SimpleDataType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SimpleDataTypeValidator {
	boolean validate();

	boolean validateBase(BaseDataType value);
}
