/** $Id$ */
package conml.types.validation;

import org.eclipse.emf.common.util.EList;

import conml.instances.ValueSet;
import conml.types.Attribute;
import conml.types.DataType;

/**
 * A sample validator interface for {@link conml.types.Attribute}. This doesn't really do anything,
 * and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can
 * be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AttributeValidator {
  boolean validate();

  boolean validateMultilingual(boolean value);

    boolean validateInstanceValueSets(EList<ValueSet> value);

        boolean validateIsMultilingual(boolean value);

  boolean validateOwner(conml.types.Class value);

  boolean validateAssignedTo(EList<conml.types.Class> value);

  boolean validateHasInstanceValueSets(EList<ValueSet> value);

  boolean validateDatatype(DataType value);

  boolean validateRedefinedAttribute(Attribute value);

    boolean validateRedefiningAttribute(Attribute value);

        boolean validateOwnerClass(conml.types.Class value);

        boolean validateRedefinedAttributes(EList<Attribute> value);

    boolean validateIsOfType(DataType value);
}
