/**
 *
 * $Id$
 */
package conml.types.validation;

import conml.types.EnumeratedItem;
import conml.types.EnumeratedType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link conml.types.EnumeratedItem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EnumeratedItemValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateAbsoluteName(String value);
	boolean validateDefinition(String value);
	boolean validateOwner(EnumeratedType value);
	boolean validateAssignedTo(EnumeratedType value);
	boolean validateIsSuperItemOf(EList<EnumeratedItem> value);
	boolean validateIsSubItemOf(EnumeratedItem value);
}
