/**
 *
 * $Id$
 */
package conml.types.validation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link conml.types.Generalization}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GeneralizationValidator {
	boolean validate();

	boolean validateDiscriminant(String value);
	boolean validateSpecializedClass(EList<conml.types.Class> value);
	boolean validateGeneralizedClass(conml.types.Class value);
	boolean validateDominatesInheritanceOn(EList<conml.types.Class> value);
}
