/**
 *
 * $Id$
 */
package conml.types.validation;

import conml.types.EnumeratedType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link conml.types.Package}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PackageValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateDescription(String value);
	boolean validateContainedClasses(EList<conml.types.Class> value);

  boolean validateContainsClass(EList<conml.types.Class> value);
	boolean validateEnumeratedTypes(EList<EnumeratedType> value);

	boolean validateSubPackages(EList<conml.types.Package> value);

  boolean validateContainerPackage(conml.types.Package value);

  boolean validateContainsEnumeratedType(EList<EnumeratedType> value);
	boolean validateIsOwnerOf(EList<conml.types.Package> value);
	boolean validateIsSubPackageOf(conml.types.Package value);

  boolean validateOverall(boolean value);
}
