/**
 *
 * $Id$
 */
package conml.types.validation;

import conml.types.TypeModel;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link conml.types.TypeModelElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TypeModelElementValidator {
	boolean validate();

	boolean validateTypeModel(TypeModel value);

  boolean validateIsAssignedTo(EList<TypeModel> value);
}
