/**
 *
 * $Id$
 */
package conml.validation;

import conml.Model;
import conml.Tag;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link conml.ModelElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModelElementValidator {
	boolean validate();

	boolean validateBelongsTo(Model value);
	boolean validateIsTaggedWith(EList<Tag> value);
	boolean validateIsDocumentedBy(EList<conml.instances.Object> value);
}
