/**
 *
 * $Id$
 */
package conml.validation;

import conml.Model;

import conml.instances.FacetSet;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link conml.Language}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LanguageValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateDescription(String value);
	boolean validateDefault(boolean value);

  boolean validateIsDefault(boolean value);
	boolean validateBelongsTo(Model value);
	boolean validateIsDefaultIn(Model value);
	boolean validateIsTranslationQualifierOf(EList<FacetSet> value);
}
