/**
 *
 * $Id$
 */
package conml.validation;

import conml.Model;
import conml.ModelElement;
import org.eclipse.emf.common.util.EList;


/**
 * A sample validator interface for {@link conml.MetaInformation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MetaInformationValidator {
	boolean validate();

	boolean validateModelElements(EList<ModelElement> value);

  boolean validateModelElement(EList<ModelElement> value);

  boolean validateObject(conml.instances.Object value);

  boolean validateModelElement(ModelElement value);

    boolean validateMetaInfoObject(conml.instances.Object value);

        boolean validateModel(Model value);
}
