/**
 *
 * $Id$
 */
package conml.validation;

import conml.Language;
import conml.ModelElement;
import conml.Tag;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link conml.Model}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModelValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateVersion(double value);

	boolean validateVersion(Object value);
	boolean validateDescription(String value);
	boolean validateHasTags(EList<Tag> value);
	boolean validateHasLanguages(EList<Language> value);
	boolean validateDefaultLanguage(Language value);
	boolean validateOwnsElements(EList<ModelElement> value);
}
