/**
 *
 * $Id$
 */
package conml.validation;

import conml.Model;
import conml.ModelElement;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link conml.Tag}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TagValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateBelongsTo(Model value);
	boolean validateAppliesTo(EList<ModelElement> value);
}
